title: Freedom Torch
description: It's free to give a shit.
baseurl: "/" 
url: "https://freedomtorch.net" 
permalink: /:year-:month-:day-:slug
twitter_handle: freedomtorch29
google_analytics: UA-87938049-1
icons_dir: /assets/icons
theme: minima
plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

      twitter_title: "Freedom Torch"
      twitter_description: ""
      twitter_image: "/assets/images/icon-64-lady-smoke.jpg"
      twitter_image_alt: "Freedom Torch"
      twitter_card_type: summary
