# Basic Information
title: Freedom Torch
description: It's free to give a shit.

# Domain Configuration
baseurl: "/" 
url: "https://freedomtorch.net" 

twitter_username: kevando_
google_analytics: UA-16078011-4

# Media
favicon: /assets/images/favicon.png

# Build settings
theme: minima
plugins:
  - jekyll-feed
