title: Freedom Torch
description: It's free to give a shit.
baseurl: "/freedom-torch" # the subpath of your site, e.g. /blog
url: "https://kevando.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Personal Info
twitter_username: kevando_
email: kevin.h@roybiv.net

# Tracking
google_analytics: UA-16078011-4

# Media
icon64: /freedom-torch/assets/images/favicon.jpg
favicon: /freedom-torch/assets/images/fav4.png
banner: /freedom-torch/assets/images/banner1.jpg
base_url_images: https://github.com/kevando/freedom-torch/blob/master/images

defaults:
  - scope:
      path: "" # all files
      type: pages
    values:
      layout: "surf"
      image: https://kevando.github.io/freedom-torch/assets/images/banner1.jpg
      title: Freedom Torch
      description: It's Free to Give a Shit

# Build settings
theme: minima
plugins:
  - jekyll-feed
