title: Freedom Torch
email: kevin.h@roybiv.net
description: It's free to give a shit.
baseurl: "/freedom-torch" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: kevando_

defaults:
  - scope:
      path: "" # all files
      type: pages
    values:
      layout: "surf"

# Build settings
theme: minima
plugins:
  - jekyll-feed
